services:
  server:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
